[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build --workspace=apps/api"]

[start]
cmd = "cd apps/api && npm start"
